name: CI/CD Pipeline

# Trigger the workflow
on:
  push:            # Runs when code is pushed
    branches: [ "main" ]
  pull_request:    # Runs on Pull Requests
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest   # Runner environment (Linux VM)

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: pytest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   # Only deploy from main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

   
